[package]
name = "stream_rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "stream_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
